export const countriesList = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Aland Islands', code: 'AX' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'Andorra', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Anguilla', code: 'AI' },
    { name: 'Antarctica', code: 'AQ' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bermuda', code: 'BM' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bonaire, Sint Eustatius and Saba', code: 'BQ' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Bouvet Island', code: 'BV' },
    { name: 'Brazil', code: 'BR' },
    { name: 'British Indian Ocean Territory', code: 'IO' },
    { name: 'Brunei Darussalam', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Cocos (Keeling) Islands', code: 'CC' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo', code: 'CG' },
    { name: 'Congo, Democratic Republic of the Congo', code: 'CD' },
    { name: 'Cook Islands', code: 'CK' },
    { name: 'Costa Rica', code: 'CR' },
    { name: "Cote D'Ivoire", code: 'CI' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Curacao', code: 'CW' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK' },
    { name: 'Faroe Islands', code: 'FO' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'French Southern Territories', code: 'TF' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Gibraltar', code: 'GI' },
    { name: 'Greece', code: 'GR' },
    { name: 'Greenland', code: 'GL' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guadeloupe', code: 'GP' },
    { name: 'Guam', code: 'GU' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guernsey', code: 'GG' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Heard Island and McDonald Islands', code: 'HM' },
    { name: 'Holy See (Vatican City State)', code: 'VA' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran, Islamic Republic of', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jersey', code: 'JE' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: "Korea, Democratic People's Republic of", code: 'KP' },
    { name: 'Korea, Republic of', code: 'KR' },
    { name: 'Kosovo', code: 'XK' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: "Lao People's Democratic Republic", code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Macao', code: 'MO' },
    { name: 'Macedonia, the Former Yugoslav Republic of', code: 'MK' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Martinique', code: 'MQ' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mayotte', code: 'YT' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia, Federated States of', code: 'FM' },
    { name: 'Moldova, Republic of', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN' },
    { name: 'New Caledonia', code: 'NC' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Niue', code: 'NU' },
    { name: 'Norfolk Island', code: 'NF' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Palestinian Territory, Occupied', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Pitcairn', code: 'PN' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Reunion', code: 'RE' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russian Federation', code: 'RU' },
    { name: 'Rwanda', code: 'RW' },
    { name: 'Saint Barthelemy', code: 'BL' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Martin', code: 'MF' },
    { name: 'Saint Pierre and Miquelon', code: 'PM' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia', code: 'RS' },
    { name: 'Serbia and Montenegro', code: 'CS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { name: 'South Sudan', code: 'SS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ' },
    { name: 'Swaziland', code: 'SZ' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syrian Arab Republic', code: 'SY' },
    { name: 'Taiwan, Province of China', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania, United Republic of', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Timor-Leste', code: 'TL' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Turks and Caicos Islands', code: 'TC' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'United States Minor Outlying Islands', code: 'UM' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Viet Nam', code: 'VN' },
    { name: 'Virgin Islands, British', code: 'VG' },
    { name: 'Virgin Islands, U.s.', code: 'VI' },
    { name: 'Wallis and Futuna', code: 'WF' },
    { name: 'Western Sahara', code: 'EH' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' },
];

export const countriesListRussian = [
    { name: 'Афганистан', code: 'AF' },
    { name: 'Аландские острова', code: 'AX' },
    { name: 'Албания', code: 'AL' },
    { name: 'Алжир', code: 'DZ' },
    { name: 'американское Самоа', code: 'AS' },
    { name: 'Андорра', code: 'AD' },
    { name: 'Ангола', code: 'AO' },
    { name: 'Ангилья', code: 'AI' },
    { name: 'Антарктида', code: 'AQ' },
    { name: 'Антигуа и Барбуда', code: 'AG' },
    { name: 'Аргентина', code: 'AR' },
    { name: 'Армения', code: 'AM' },
    { name: 'Аруба', code: 'AW' },
    { name: 'Австралия', code: 'AU' },
    { name: 'Австрия', code: 'AT' },
    { name: 'Азербайджан', code: 'AZ' },
    { name: 'Багамы', code: 'BS' },
    { name: 'Бахрейн', code: 'BH' },
    { name: 'Бангладеш', code: 'BD' },
    { name: 'Барбадос', code: 'BB' },
    { name: 'Беларусь', code: 'BY' },
    { name: 'Бельгия', code: 'BE' },
    { name: 'Белиз', code: 'BZ' },
    { name: 'Бенин', code: 'BJ' },
    { name: 'Бермуды', code: 'BM' },
    { name: 'Бутан', code: 'BT' },
    { name: 'Боливия', code: 'BO' },
    { name: 'Бонэйр, Синт-Эстатиус и Саба', code: 'BQ' },
    { name: 'Босния и Герцеговина', code: 'BA' },
    { name: 'Ботсвана', code: 'BW' },
    { name: 'Остров Буве', code: 'BV' },
    { name: 'Бразилия', code: 'BR' },
    { name: 'Британская территория Индийского океана', code: 'IO' },
    { name: 'Бруней-Даруссалам', code: 'BN' },
    { name: 'Болгария', code: 'BG' },
    { name: 'Буркина-Фасо', code: 'BF' },
    { name: 'Бурунди', code: 'BI' },
    { name: 'Камбоджа', code: 'KH' },
    { name: 'Камерун', code: 'CM' },
    { name: 'Канада', code: 'CA' },
    { name: 'Кабо-Верде', code: 'CV' },
    { name: 'Каймановы острова', code: 'KY' },
    { name: 'Центрально-Африканская Республика', code: 'CF' },
    { name: 'Чад', code: 'TD' },
    { name: 'Чили', code: 'CL' },
    { name: 'Китай', code: 'CN' },
    { name: 'Остров Рождества', code: 'CX' },
    { name: 'Кокосовые (Килинг) острова', code: 'CC' },
    { name: 'Колумбия', code: 'CO' },
    { name: 'Коморские острова', code: 'KM' },
    { name: 'Конго', code: 'CG' },
    { name: 'Конго, Демократическая Республика Конго', code: 'CD' },
    { name: 'Острова Кука', code: 'CK' },
    { name: 'Коста-Рика', code: 'CR' },
    { name: 'Берег Слоновой Кости', code: 'CI' },
    { name: 'Хорватия', code: 'HR' },
    { name: 'Куба', code: 'CU' },
    { name: 'Кюрасао', code: 'CW' },
    { name: 'Кипр', code: 'CY' },
    { name: 'Чехия', code: 'CZ' },
    { name: 'Дания', code: 'DK' },
    { name: 'Джибути', code: 'DJ' },
    { name: 'Доминика', code: 'DM' },
    { name: 'Доминиканская Республика', code: 'DO' },
    { name: 'Эквадор', code: 'EC' },
    { name: 'Египет', code: 'EG' },
    { name: 'Эль Сальвадор', code: 'SV' },
    { name: 'Экваториальная Гвинея', code: 'GQ' },
    { name: 'Эритрея', code: 'ER' },
    { name: 'Эстония', code: 'EE' },
    { name: 'Эфиопия', code: 'ET' },
    { name: 'Фолклендские (Мальвинские) острова', code: 'FK' },
    { name: 'Фарерские острова', code: 'FO' },
    { name: 'Фиджи', code: 'FJ' },
    { name: 'Финляндия', code: 'FI' },
    { name: 'Франция', code: 'FR' },
    { name: 'Французская Гвиана', code: 'GF' },
    { name: 'Французская Полинезия', code: 'PF' },
    { name: 'Южные Французские Территории', code: 'TF' },
    { name: 'Габон', code: 'GA' },
    { name: 'Гамбия', code: 'GM' },
    { name: 'Грузия', code: 'GE' },
    { name: 'Германия', code: 'DE' },
    { name: 'Гана', code: 'GH' },
    { name: 'Гибралтар', code: 'GI' },
    { name: 'Греция', code: 'GR' },
    { name: 'Гренландия', code: 'GL' },
    { name: 'Гренада', code: 'GD' },
    { name: 'Гваделупа', code: 'GP' },
    { name: 'Гуам', code: 'GU' },
    { name: 'Гватемала', code: 'GT' },
    { name: 'Гернси', code: 'GG' },
    { name: 'Гвинея', code: 'GN' },
    { name: 'Гвинея-Бисау', code: 'GW' },
    { name: 'Гайана', code: 'GY' },
    { name: 'Гаити', code: 'HT' },
    { name: 'Остров Херд и острова Макдональд', code: 'HM' },
    { name: 'Святой Престол (государство-город Ватикан)', code: 'VA' },
    { name: 'Гондурас', code: 'HN' },
    { name: 'Гонконг', code: 'HK' },
    { name: 'Венгрия', code: 'HU' },
    { name: 'Исландия', code: 'IS' },
    { name: 'Индия', code: 'IN' },
    { name: 'Индонезия', code: 'ID' },
    { name: 'Иран, Исламская Республика', code: 'IR' },
    { name: 'Ирак', code: 'IQ' },
    { name: 'Ирландия', code: 'IE' },
    { name: 'Остров Мэн', code: 'IM' },
    { name: 'Израиль', code: 'IL' },
    { name: 'Италия', code: 'IT' },
    { name: 'Ямайка', code: 'JM' },
    { name: 'Япония', code: 'JP' },
    { name: 'Джерси', code: 'JE' },
    { name: 'Иордания', code: 'JO' },
    { name: 'Казахстан', code: 'KZ' },
    { name: 'Кения', code: 'KE' },
    { name: 'Кирибати', code: 'KI' },
    { name: 'Корея, Народно-Демократическая Республика', code: 'KP' },
    { name: 'Корея, Республика', code: 'KR' },
    { name: 'Косово', code: 'XK' },
    { name: 'Кувейт', code: 'KW' },
    { name: 'Кыргызстан', code: 'KG' },
    { name: 'Лаосская Народно-Демократическая Республика', code: 'LA' },
    { name: 'Латвия', code: 'LV' },
    { name: 'Ливан', code: 'LB' },
    { name: 'Лесото', code: 'LS' },
    { name: 'Либерия', code: 'LR' },
    { name: 'Ливийская арабская джамахирия', code: 'LY' },
    { name: 'Лихтенштейн', code: 'LI' },
    { name: 'Литва', code: 'LT' },
    { name: 'Люксембург', code: 'LU' },
    { name: 'Макао', code: 'MO' },
    { name: 'Македония, бывшая югославская Республика', code: 'MK' },
    { name: 'Мадагаскар', code: 'MG' },
    { name: 'Малави', code: 'MW' },
    { name: 'Малайзия', code: 'MY' },
    { name: 'Мальдивы', code: 'MV' },
    { name: 'Мали', code: 'ML' },
    { name: 'Мальта', code: 'MT' },
    { name: 'Маршалловы острова', code: 'MH' },
    { name: 'Мартиника', code: 'MQ' },
    { name: 'Мавритания', code: 'MR' },
    { name: 'Маврикий', code: 'MU' },
    { name: 'Майотта', code: 'YT' },
    { name: 'Мексика', code: 'MX' },
    { name: 'Микронезия, Федеративные Штаты', code: 'FM' },
    { name: 'Молдова, Республика', code: 'MD' },
    { name: 'Монако', code: 'MC' },
    { name: 'Монголия', code: 'MN' },
    { name: 'Черногория', code: 'ME' },
    { name: 'Монтсеррат', code: 'MS' },
    { name: 'Марокко', code: 'MA' },
    { name: 'Мозамбик', code: 'MZ' },
    { name: 'Мьянма', code: 'MM' },
    { name: 'Намибия', code: 'NA' },
    { name: 'Науру', code: 'NR' },
    { name: 'Непал', code: 'NP' },
    { name: 'Нидерланды', code: 'NL' },
    { name: 'Нидерландские Антильские острова', code: 'AN' },
    { name: 'Новая Каледония', code: 'NC' },
    { name: 'Новая Зеландия', code: 'NZ' },
    { name: 'Никарагуа', code: 'NI' },
    { name: 'Нигер', code: 'NE' },
    { name: 'Нигерия', code: 'NG' },
    { name: 'Ниуэ', code: 'NU' },
    { name: 'Остров Норфолк', code: 'NF' },
    { name: 'Северные Марианские острова', code: 'MP' },
    { name: 'Норвегия', code: 'NO' },
    { name: 'Оман', code: 'OM' },
    { name: 'Пакистан', code: 'PK' },
    { name: 'Палау', code: 'PW' },
    { name: 'Палестинская территория, оккупированная', code: 'PS' },
    { name: 'Панама', code: 'PA' },
    { name: 'Папуа - Новая Гвинея', code: 'PG' },
    { name: 'Парагвай', code: 'PY' },
    { name: 'Перу', code: 'PE' },
    { name: 'Филиппины', code: 'PH' },
    { name: 'Питкэрн', code: 'PN' },
    { name: 'Польша', code: 'PL' },
    { name: 'Португалия', code: 'PT' },
    { name: 'Пуэрто-Рико', code: 'PR' },
    { name: 'Катар', code: 'QA' },
    { name: 'Воссоединение', code: 'RE' },
    { name: 'Румыния', code: 'RO' },
    { name: 'Российская Федерация', code: 'RU' },
    { name: 'Руанда', code: 'RW' },
    { name: 'Сен-Бартелеми', code: 'BL' },
    { name: 'Святой Елены', code: 'SH' },
    { name: 'Сент-Китс и Невис', code: 'KN' },
    { name: 'Сент-Люсия', code: 'LC' },
    { name: 'Сен-Мартен', code: 'MF' },
    { name: 'Сен-Пьер и Микелон', code: 'PM' },
    { name: 'Святой Винсент и Гренадины', code: 'VC' },
    { name: 'Самоа', code: 'WS' },
    { name: 'Сан-Марино', code: 'SM' },
    { name: 'Сан-Томе и Принсипи', code: 'ST' },
    { name: 'Саудовская Аравия', code: 'SA' },
    { name: 'Сенегал', code: 'SN' },
    { name: 'Сербия', code: 'RS' },
    { name: 'Сербия и Черногория', code: 'CS' },
    { name: 'Сейшельские острова', code: 'SC' },
    { name: 'Сьерра-Леоне', code: 'SL' },
    { name: 'Сингапур', code: 'SG' },
    { name: 'Словакия', code: 'SK' },
    { name: 'Словения', code: 'SI' },
    { name: 'Соломоновы острова', code: 'SB' },
    { name: 'Сомали', code: 'SO' },
    { name: 'Южная Африка', code: 'ZA' },
    { name: 'Южная Георгия и Южные Сандвичевы острова', code: 'GS' },
    { name: 'южный Судан', code: 'SS' },
    { name: 'Испания', code: 'ES' },
    { name: 'Шри-Ланка', code: 'LK' },
    { name: 'Судан', code: 'SD' },
    { name: 'Суринам', code: 'SR' },
    { name: 'Шпицберген и Ян Майен', code: 'SJ' },
    { name: 'Свазиленд', code: 'SZ' },
    { name: 'Швеция', code: 'SE' },
    { name: 'Швейцария', code: 'CH' },
    { name: 'Сирийская Арабская Республика', code: 'SY' },
    { name: 'Тайвань, провинция Китая', code: 'TW' },
    { name: 'Таджикистан', code: 'TJ' },
    { name: 'Танзания, Объединенная Республика', code: 'TZ' },
    { name: 'Таиланд', code: 'TH' },
    { name: 'Тимор-Лешти', code: 'TL' },
    { name: 'Идти', code: 'TG' },
    { name: 'Токелау', code: 'TK' },
    { name: 'Тонга', code: 'TO' },
    { name: 'Тринидад и Тобаго', code: 'TT' },
    { name: 'Тунис', code: 'TN' },
    { name: 'индюк', code: 'TR' },
    { name: 'Туркменистан', code: 'TM' },
    { name: 'Острова Теркс и Кайкос', code: 'TC' },
    { name: 'Тувалу', code: 'TV' },
    { name: 'Уганда', code: 'UG' },
    { name: 'Украина', code: 'UA' },
    { name: 'Объединенные Арабские Эмираты', code: 'AE' },
    { name: 'объединенное Королевство', code: 'GB' },
    { name: 'Соединенные Штаты', code: 'US' },
    { name: 'Внешние малые острова США', code: 'UM' },
    { name: 'Уругвай', code: 'UY' },
    { name: 'Узбекистан', code: 'UZ' },
    { name: 'Вануату', code: 'VU' },
    { name: 'Венесуэла', code: 'VE' },
    { name: 'Вьетнам', code: 'VN' },
    { name: 'Виргинские острова, Британские', code: 'VG' },
    { name: 'Виргинские острова, США', code: 'VI' },
    { name: 'Уоллис и Футуна', code: 'WF' },
    { name: 'Западная Сахара', code: 'EH' },
    { name: 'Йемен', code: 'YE' },
    { name: 'Замбия', code: 'ZM' },
    { name: 'Зимбабве', code: 'ZW' },
];
